# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-db.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    application:
        name: Ejercicio
    profiles:
        active: db
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ejercicio
        username: postgres
        password: postgres
    jpa:
        hibernate:
        ddl-auto: create
        naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        openInView: false
        show_sql: true
        generate-ddl: true

