# ===================================================================
# Spring Boot configuration for the "ldap" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ejercicio
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: postgresql
        openInView: false
        show_sql: true
        generate-ddl: true
