package com.mycompany.ejercicio.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-02-21T22:35:25.627-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://mycompany.com/ejercicio/cxf", name = "RolePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RolePortType {

    @WebMethod(operationName = "RoleDetails")
    @WebResult(name = "role", targetNamespace = "", partName = "role")
    public Role roleDetails(
        @WebParam(partName = "id", name = "id", targetNamespace = "")
        int id
    );
}
