package com.mycompany.ejercicio.cxf;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-02-21T21:50:30.712-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "RoleService", 
                  wsdlLocation = "classpath:wsdl/WSDLEjercicio.wsdl",
                  targetNamespace = "http://mycompany.com/ejercicio/cxf") 
public class RoleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mycompany.com/ejercicio/cxf", "RoleService");
    public final static QName RolePort = new QName("http://mycompany.com/ejercicio/cxf", "RolePort");
    static {
        URL url = RoleService.class.getClassLoader().getResource("wsdl/WSDLEjercicio.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RoleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/WSDLEjercicio.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public RoleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RoleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RoleService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RoleService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RoleService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RolePortType
     */
    @WebEndpoint(name = "RolePort")
    public RolePortType getRolePort() {
        return super.getPort(RolePort, RolePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolePortType
     */
    @WebEndpoint(name = "RolePort")
    public RolePortType getRolePort(WebServiceFeature... features) {
        return super.getPort(RolePort, RolePortType.class, features);
    }

}
